name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
      - working-directory: ./cdk 
        run: |
          npm ci
          npm run lint
          npm run test
          npm run synth
      - name: test and check formatting
        run: |
          sbt -v test scalafmtCheckAll
      - name: build uberjar
        run: |
          sbt -v assembly

      - uses: guardian/actions-riff-raff@v1
        with:
          app: backend-103-LAKSHMIRPILLAI
          config: | 
            stacks:
              - deploy
            regions:
              - eu-west-1
            allowedStages:
              - CODE
            deployments:
              cloudformation:
                type: cloud-formation
                app: backend-103-LAKSHMIRPILLAI
                sources:
                  - cdk/cdk.out/Backend103Lakshmirpillai-CODE.template.json
                parameters:
                  amiParameter: AMIBackend103LAKSHMIRPILLAI
                  amiTags:
                    BuiltBy: amigo
                    Recipe: backend-101
                    AmigoStage: PROD
                  templatePath: Backend103Lakshmirpillai-CODE.template.json 
              backend-103-LAKSHMIRPILLAI: 
                type: autoscaling
                sources:
                  - target/scala-2.13/hello-world.jar
                  - app.service 
                parameters:
                  bucket: deploy-tools-dist 
                dependencies:
                  - cloudformation